### ISSUE TITLE
"Manual book"

### ISSUE THREAD

**Issue by OlavHjortas** [KvaGram/Untitled-the-adventure-game#4]
I don't understand the meaning of this expression, found in the following narrative:

`You got the manual book in your hand, but your fingers are now covered in a layor of some oily substance.`

**Comment by KvaGram** [comment]
The narrative is made to suggest your fingers got stuck in time.
The oily substance is meant to be cooling liquid or something like that from the near future, after the module had exploded. But off course, you would have no way of knowing that (yet).
Issue will remain open until I find a way to improve this narrative.
Any suggestions are welcome.
